# Executable name
BIN = BoundBuf

# Directories
OBJ_DIR=obj
BIN_DIR=bin

# Linker, version, and misc additions
CC=cc
VERSION=-std=c++11

# All call
all: directories programs

# Make all of these directories if they don't exist
directories:
	@mkdir -p $(OBJ_DIR)
	@mkdir -p $(BIN_DIR)

src_comp: src/*.cpp
	$(subst %,Producer, $(CC) $(VERSION) -c src/%.cpp -o $(OBJ_DIR)/%.o)
	$(subst %,Consumer, $(CC) $(VERSION) -c src/%.cpp -o $(OBJ_DIR)/%.o)
	$(subst %,Main, $(CC) $(VERSION) -c src/%.cpp -o $(OBJ_DIR)/%.o)

program: src_comp
	g++ $(OBJ_DIR)/*.o -o $(BIN_DIR)/$(BIN)

# Clean does a recursive removal of the generated bin and obj directories.
.PHONY: clean
clean:
	rm -rf $(OBJ_DIR)
	rm -rf $(BIN_DIR)
